postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: "postgres"
        database: "k8s-training"
  primary:
    persistence:
      enabled: true
      size: 1Gi
    initdb:
      scriptsConfigMap: "k8s-training-config"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi    
app:
  image: thomassamson33/k8s-training
  tag: ex-9