apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-training
  name: k8s-training-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: k8s-training
