apiVersion: v1
kind: Service
metadata:
  name: k8s-training-postgres-service
  labels:
    app: k8s-training-postgres
spec:
  # Il est aussi possible d'utiliser un service headless :
  #clusterIP: None
  # Dans ce cas ce service sert uniquement à générer
  # des noms de domaines pour chaque pod du type:
  # k8s-training-postgres-{0..N-1}.k8s-training-postgres-service.default.svc.cluster.local
  ports:
  - port: 5432
    name: tcp-postgresql
  selector:
    app: k8s-training-postgres
