<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDYK5rOp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDYK5rOp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDYK5rOp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDYK5rOp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDYK5rOp\App_KernelDevDebugContainer([
    'container.build_hash' => 'DYK5rOp',
    'container.build_id' => '66ea9306',
    'container.build_time' => 1731580073,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDYK5rOp');
