apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-training-config
  namespace: default
data:
  postgres-database: k8s-training
  postgres-fixtures.sql: |+
    CREATE TABLE IF NOT EXISTS stuff (
        id SERIAL PRIMARY KEY,
        name VARCHAR NOT NULL
    );

    INSERT INTO stuff(name) VALUES
        ('Kubernetes'),
        ('Mercure'),
        ('Vulcain'),
        ('API Platform'),
        ('FrankenPHP')
    ;

  postgres-host: k8s-training-postgres-service
  postgres-username: postgres
